apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-kursor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kargo-kursor
  template:
    metadata:
      labels:
        app: kargo-kursor
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: kargo-kursor
        image: 274199647570.dkr.ecr.us-east-1.amazonaws.com/kargo-kursor:dev 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20 