apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kargo-kursor
  annotations:
    tailscale.com/tags: tag:k8s-apps-brand-dev
    tailscale.com/force-https: "true"
  finalizers:
  - tailscale.com/finalizer
  labels:
    app: kargo-kursor
    environment: dev
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - kargo-kursor.kargo.ts.net
  rules:
    - host: kargo-kursor.kargo.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kargo-kursor
                port:
                  number: 80